version: '3.8'

services:
    metabase:
        image: metabase/metabase:latest
        ports:
            - '3000:3000'
        volumes:
            - '.cache/metabase:/metabase.db'

    publisher:
        build:
            context: .
            dockerfile: Dockerfile
        command: cargo run --bin publisher
        volumes:
            - .:/usr/src/workspace

    subscriber:
        build:
            context: .
            dockerfile: Dockerfile
        command: cargo run --bin subscriber
        volumes:
            - .:/usr/src/workspace
