[package]
name = "common"
version = "0.1.0"
edition = "2021"
authors = ["Vinicios Lugli <vinicioslugli@gmail.com>"]

[dependencies]

paho-mqtt = { version = "0.12.3", features = ["vendored-ssl"] }
dotenvy = "0.15.7"
rand = "0.8.5"
