[package]
name = "publisher"
version = "0.1.0"
edition = "2021"
authors = ["Vinicios Lugli <vinicioslugli@gmail.com>"]

[dependencies]
common = { path = "../common" }
rand = "0.8.5"
serde_json = "1.0.114"
